[package]
name = "secure-env"
version = "0.1.0"
edition = "2021"

[lib]
name = "secure_env"
crate-type = ["cdylib", "rlib"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = { version = "2.9.2", features = ["OSX_10_12"] }
p256 = { version = "0.13.2", features = ["ecdsa-core"] }

# [target.'cfg(target_os = "android")'.dependencies]
[dependencies]
android-activity = { version = "0.5.0", features = ["native-activity"] }
jni = { version = "0.21.1", features = ["invocation"] }
ndk-context = "0.1.1"
lazy_static = "1.4.0"

[dev-dependencies]
askar-crypto = "0.3.0"
sha2 = { version = "0.10.8", default-features = false }
