name: Crates.io Release

env:
  RUST_VERSION: "1.74"

on:
  workflow_dispatch:
    
jobs:
  release-crates:
    name: Release crates.io
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v4

        - name: Install Rust Toolchain
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: ${{ env.RUST_VERSION }}
            targets: aarch64-apple-ios

        - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --target=aarch64-apple-ios
