name: Crates.io Release

on:
  workflow_dispatch:
    
jobs:
  release-crates:
    name: Release crates.io
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
