name: Check

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_VERSION: "1.65.0"

jobs:
  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy

    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            runner: ubuntu-latest
          - target: aarch64-apple-darwin
            runner: macos-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}
          components: clippy

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo clippy --target=${{ matrix.target }}

  audit:
    name: Audit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo audit

  check:
    name: Check

    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            runner: ubuntu-latest
          - target: aarch64-apple-darwin
            runner: macos-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo check --target=${{ matrix.target }}
