name: Check

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main


# TODO: check on target ios and android

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    name: Clippy
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo clippy

  audit:
    runs-on: ubuntu-latest
    name: Audit
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo audit

  check:
    runs-on: ubuntu-latest
    name: Check
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true

      - run: cargo check
